### ISSUE TITLE
Have You Looked into TypeScript?

### ISSUE THREAD

**Issue by say25** [cuappdev/bible#3]
Using TypeScript has many advantages. Support for it is easy and provides many advantages. 

Sample Node Tutorial:
https://blog.risingstack.com/building-a-node-js-app-with-typescript-tutorial/

Just wanted to see if you guys have thought about it?

**Comment by Jma353** [comment]
Yup, Flow and TypeScript have extremely similar advantages, with Flow coming out on top when it comes to writing React.  Writing a Node.js server in TypeScript vs. Flow + ES6 is an extremely similar experience.

Rather than setting up two different development environments to write JS, I opted to write one that works for both client-side and server-side.

Thanks for the suggestion though, appreciate the input.
